### ISSUE TITLE
Compile problem in ngx_utils.c on ubuntu 16

### ISSUE THREAD

**Issue by jiristerba** [gfleury/nginx_mod_cluster_module#3]
Hi, can you help me with this error :   Thanks  Jiri

```
/opt/nginx_mod_cluster_module/advertise//ngx_utils.c
```

/opt/nginx_mod_cluster_module/advertise//ngx_utils.c: In function 'ngx_parse_addr_port':
/opt/nginx_mod_cluster_module/advertise//ngx_utils.c:100:13: error: implicit declaration of function 'apr_palloc' [-Werror=implicit-function-declaration]
             *scope_id = apr_palloc(p, end_bracket - scope_delim);
             ^
/opt/nginx_mod_cluster_module/advertise//ngx_utils.c:100:23: error: assignment makes pointer from integer without a cast [-Werror]
             *scope_id = apr_palloc(p, end_bracket - scope_delim);
                       ^
/opt/nginx_mod_cluster_module/advertise//ngx_utils.c:112:9: error: implicit declaration of function 'apr_inet_pton' [-Werror=implicit-function-declaration]
         if (apr_inet_pton(AF_INET6, *addr, &ipaddr) != 1) {
         ^
/opt/nginx_mod_cluster_module/advertise//ngx_utils.c: In function 'get_random_info':
/opt/nginx_mod_cluster_module/advertise//ngx_utils.c:257:13: error: ignoring return value of 'read', declared with attribute warn_unused_result [-Werror=unused-result]
         read(fd, seed, 16);
             ^

**Comment by gfleury** [comment]
I never used with ipv6 support, but its easy to fix this. Will fix and warn you.

**Comment by jiristerba** [comment]
Hi,

Thanks a lot.
Best regards

Jiří Štěrba
