### ISSUE TITLE
Don't make - [-Werror=unused-function]

### ISSUE THREAD

**Issue by zerocrow** [gfleury/nginx_mod_cluster_module#4]
Hello!!
Wanting compile gives me the following error (probe with the new version and 1.5)

With nginx 1.5.13:

Error: #....nginx_mod_cluster_module-master/advertise//ngx_utils.c:38:1: error: se define ‘inet_pton4’ pero no se usa [-Werror=unused-function]

./configure --add-module=##/nginx_mod_cluster_module-master/advertise/ --add-module=###/nginx_mod_cluster_module-master/manager/ && make

with nginx 1.11.4

/home/crow/Descargas/nginx_mod_cluster_module-master/advertise//ngx_http_advertise_module.c In file included from /home/crow/Descargas/nginx_mod_cluster_module-master/advertise//ngx_http_advertise_module.c:18:0:
/home/crow/Descargas/nginx_mod_cluster_module-master/advertise//../include/ngx_utils.h:25:11: error: tipos en conflicto para ‘ngx_parse_addr_port’
 ngx_int_t ngx_parse_addr_port(u_char *_addr, u_char *_scope_id, ngx_uint_t _port, const u_char *str, ngx_pool_t *p);
           ^
In file included from src/core/ngx_core.h:79:0,
                 from /home/crow/Descargas/nginx_mod_cluster_module-master/advertise//ngx_http_advertise_module.c:11:
src/core/ngx_inet.h:119:11: nota: la declaración previa de ‘ngx_parse_addr_port’ estaba aquí
 ngx_int_t ngx_parse_addr_port(ngx_pool_t *pool, ngx_addr_t *addr,
           ^
In file included from /home/crow/Descargas/nginx_mod_cluster_module-master/advertise//ngx_http_advertise_module.c:18:0:
/home/crow/Descargas/nginx_mod_cluster_module-master/advertise//../include/ngx_utils.h:191:3: error: tipos en conflicto para ‘ngx_sockaddr_t’
 } ngx_sockaddr_t;
   ^
In file included from src/core/ngx_core.h:79:0,
                 from /home/crow/Descargas/nginx_mod_cluster_module-master/advertise//ngx_http_advertise_module.c:11:
src/core/ngx_inet.h:43:3: nota: la declaración previa de ‘ngx_sockaddr_t’ estaba aquí
 } ngx_sockaddr_t;
   ^
make[1]: *_\* [objs/addon/advertise/ngx_http_advertise_module.o] Error 1
make[1]: se sale del directorio `/home/crow/Descargas/nginx-1.11.4'
make: **\* [build] Error 2

Os: Centos 7 x86_64

I'd appreciate if you prune help me get rid of apache hehe

**Comment by gfleury** [comment]
Hey, sorry this is happening because i never test without SSL and IPV6 enabled. But its fixed, git pull, should work now, tested against nginx-1.5.9, unfortunately NGINX changed a lot of stuffs in newer versions so o you only be able to compile it against 1.6 or older versions.

**Comment by zerocrow** [comment]
Thank you very much!
It works ok!

**Comment by gfleury** [comment]
Hey, let me know if you want some help with the config files, there is some caveats to get everything working. @zerocrow

**Comment by zerocrow** [comment]
Hello, again
You could pass me a complete example configuration?
in AdvertiseSecurityKey seckey; which would be the key?
Thank you very much for the help

**Comment by gfleury** [comment]
@zerocrow seckey is the secret key shared between the java endpoints (ex, wildfly + mod_cluster) and the nginx mod_cluster. You already use apache with mod_cluster? If you use just check if you are using secret key, if you are not you can just ignore this option.

**Comment by zerocrow** [comment]
I imagined LOL
Thank you very much for your help! Excellent work! I served a lot. I am now in testing stage, we will look as follows.
regards

**Comment by gfleury** [comment]
@zerocrow fine, if you need something just ask.
