### ISSUE TITLE
default_port removed in nginx 1.11.6 and up.

### ISSUE THREAD

**Issue by larssn** [gfleury/nginx_mod_cluster_module#5]
Will cause compilation problems because of this.

See https://github.com/openresty/redis2-nginx-module/commit/8cc7304787ae9542db4feb50d9e27beb485caa0f

**Comment by gfleury** [comment]
Hey @larssn, actually this module only can be compiled with nginx-release-1.6.3.  Newer versions has a different module approach. But thanks for the advice.

**Comment by larssn** [comment]
Ah, oh well. :)
